### Obtener todos los usuarios
GET http://localhost:8081/usuario

### Crear nuevo usuario
POST http://localhost:8081/usuario
Content-Type: application/json

{
  "user": "mendesj",
  "passwords": "12345",
  "name": "Jaimito",
  "lastname": "Mendez",
  "area": "administracion",
  "mail": "mendesj@noreply.com",
  "first": true
}

### Actualizar usuario
PUT http://localhost:8081/usuario/15
Content-Type: application/json

{
  "user": "abcd",
  "passwords": "asdab"
}

### Eliminar Usuario
DELETE http://localhost:8081/usuario/1

### Obtener un usuario
GET http://localhost:8081/usuario/1

### Login
POST http://localhost:8081/usuario/login
Content-Type: application/json

{
  "passwords": "12345",
  "user": "mendesj"
}

### Actualizar usuario
PUT http://localhost:8081/usuario/2
Content-Type: application/json

{
  "user": "mendesj",
  "passwords": "12345",
  "name": "Jaimito",
  "lastname": "Mendez",
  "area": "administracion",
  "mail": "mendesj@noreply.com",
  "first": false
}

### Actualizar contrasenia
PUT http://localhost:8081/usuario/passChange/2
Content-Type: application/json

{
  "passwords": "123"
}